localStorage.setItem("site",window.location.origin);let fontfamily,bkgrdcolor,prmytextcolor,secdrytextcolor,acctcolor,secacctcolor,tertaccentcolor;const abcloakelement=document.getElementById("abtoggle");const confirmabcloak=document.getElementById("confirmabcloak");const confirmnormal=document.getElementById("confirmnormal");const tabinput=document.getElementById("tabcloak-input");const favicon=document.getElementById("favicon");const panickeyinput=document.getElementById("panic-key-input");const panicurlinput=document.getElementById("panic-site-input");const rootelement=document.querySelector(':root');const fontinput=document.getElementById('customization-custom-theme-font-input');const backgroundcolor=document.getElementById('backgroundcolor');const primarytextcolor=document.getElementById('primarytextcolor');const secondarytextcolor=document.getElementById('secondarytextcolor');const accentcolor=document.getElementById('accentcolor');const secondaryaccentcolor=document.getElementById('secondaryaccentcolor');const tertiaryaccentcolor=document.getElementById('tertiaryaccentcolor');const defaulttheme=document.getElementById('theme-default');const darktheme=document.getElementById('theme-dark');const oceantheme=document.getElementById('theme-ocean');const morningtheme=document.getElementById('theme-morning');const cherryblossomtheme=document.getElementById('theme-cherryblossom');const nighttheme=document.getElementById('theme-night');const seasonaltheme=document.getElementById('theme-seasonal');const customtheme=document.getElementById('theme-custom');if(!(getItem("theme"))){setItem("theme","default");setDefaultTheme();}else{if(getItem('fontfamily')){fontfamily=getItem('fontfamily');fontinput.value=fontfamily;}
if(getItem('backgroundcolor')){bkgrdcolor=getItem('backgroundcolor');backgroundcolor.value=bkgrdcolor;}
if(getItem('primarytextcolor')){prmytextcolor=getItem('primarytextcolor');primarytextcolor.value=prmytextcolor;}
if(getItem('secondarytextcolor')){secdrytextcolor=getItem('secondarytextcolor');secondarytextcolor.value=secdrytextcolor;}
if(getItem('accentcolor')){acctcolor=getItem('accentcolor');accentcolor.value=acctcolor;}
if(getItem('secondaryaccentcolor')){secacctcolor=getItem('secondaryaccentcolor');secondaryaccentcolor.value=secacctcolor;}
if(getItem('tertiaryaccentcolor')){tertaccentcolor=getItem('tertiaryaccentcolor');tertiaryaccentcolor.value=tertaccentcolor;}
themeName=getItem("theme");switch(themeName){case "dark":setDarkTheme();darktheme.classList.add('active-theme-button');break;case "ocean":setOceanTheme();oceantheme.classList.add('active-theme-button');break;case "morning":setMorningTheme();morningtheme.classList.add('active-theme-button');break;case "cherryblossom":setCherryTheme();cherryblossomtheme.classList.add('active-theme-button');break;case "night":setNightTheme();nighttheme.classList.add('active-theme-button');break;case "seasonal":setSeasonalTheme();seasonaltheme.classList.add('active-theme-button');break;case "custom":setCustomTheme(fontfamily,bkgrdcolor,prmytextcolor,secdrytextcolor,acctcolor,secacctcolor,tertaccentcolor);customtheme.classList.add('active-theme-button');break;default:setDefaultTheme();defaulttheme.classList.add('active-theme-button');}}
window.addEventListener('load',function(){if(getItem("abcloakingstatus")==null)setItem("abcloakingstatus","true");abcloakingstatus=getItem("abcloakingstatus");if(abcloakingstatus=="true"&&window.top.location.href!=="about:blank"){abcloakelement.checked=true;confirmabcloak.style.visibility="visible";}
if(window.top.location.href=="about:blank"&&abcloakingstatus=="true"){abcloakelement.checked=true;}
if(getItem("pageiconurl")){favicon.href=getItem("pageiconurl");}
if(getItem("pagetitle")){document.title=getItem("pagetitle");}
if(getItem("panickey")){panickeyinput.value=getItem("panickey");panickey=getItem("panickey");}
else{panickey="Escape";panickeyinput.value=panickey;}
if(getItem("panicurl")){panicurlinput.value=getItem("panicurl");panicurl=getItem("panicurl");}
else{panicurl="google.com";panicurlinput.value=panicurl;}
addEventListener('keydown',(event)=>{if(event.key==panickey){window.open(httpsUrl(panicurl),'_blank').focus();}});})
fontinput.addEventListener('change',(event)=>{fontfamily=event.target.value;setItem('fontfamily',fontfamily);if(customtheme.classList.contains('active-theme-button')){setRootProperty("--primary-font",`'${getItem('fontfamily')}', sans-serif`);}else{setRootProperty("--primary-font",`'Dosis', sans-serif`);}})
backgroundcolor.addEventListener('input',(event)=>{bkgrdcolor=event.target.value;setItem('backgroundcolor',bkgrdcolor);if(customtheme.classList.contains('active-theme-button')){setRootProperty("--backgroundcolor",getItem('backgroundcolor'));}})
primarytextcolor.addEventListener('input',(event)=>{prmytextcolor=event.target.value;setItem('primarytextcolor',prmytextcolor);if(customtheme.classList.contains('active-theme-button')){setRootProperty("--primarytextcolor",getItem('primarytextcolor'));}})
secondarytextcolor.addEventListener('input',(event)=>{secdrytextcolor=event.target.value;setItem('secondarytextcolor',secdrytextcolor);if(customtheme.classList.contains('active-theme-button')){setRootProperty("--secondarytextcolor",getItem('secondarytextcolor'));}})
accentcolor.addEventListener('input',(event)=>{acctcolor=event.target.value;setItem('accentcolor',acctcolor);if(customtheme.classList.contains('active-theme-button')){setRootProperty("--accentcolor",getItem('accentcolor'));}})
secondaryaccentcolor.addEventListener('input',(event)=>{secacctcolor=event.target.value;setItem('secondaryaccentcolor',secacctcolor);if(customtheme.classList.contains('active-theme-button')){setRootProperty("--secondaryaccentcolor",getItem('secondaryaccentcolor'));}})
tertiaryaccentcolor.addEventListener('input',(event)=>{tertaccentcolor=event.target.value;setItem('tertiaryaccentcolor',tertaccentcolor);if(customtheme.classList.contains('active-theme-button')){setRootProperty("--tertiaryaccentcolor",getItem('tertiaryaccentcolor'));}})
function themeButtonListenener(theme){darktheme.classList.remove('active-theme-button');oceantheme.classList.remove('active-theme-button');morningtheme.classList.remove('active-theme-button');cherryblossomtheme.classList.remove('active-theme-button');nighttheme.classList.remove('active-theme-button');seasonaltheme.classList.remove('active-theme-button');customtheme.classList.remove('active-theme-button');defaulttheme.classList.remove('active-theme-button');switch(theme){case "theme-dark":setDarkTheme();setItem("theme","dark");darktheme.classList.add('active-theme-button');break;case "theme-ocean":setOceanTheme();setItem("theme","ocean");oceantheme.classList.add('active-theme-button');break;case "theme-morning":setMorningTheme();setItem("theme","morning");morningtheme.classList.add('active-theme-button');break;case "theme-cherryblossom":setCherryTheme();setItem("theme","cherryblossom");cherryblossomtheme.classList.add('active-theme-button');break;case "theme-night":setNightTheme();setItem("theme","night");nighttheme.classList.add('active-theme-button');break;case "theme-seasonal":setSeasonalTheme();setItem("theme","seasonal");seasonaltheme.classList.add('active-theme-button');break;case "theme-custom":setCustomTheme(fontfamily,bkgrdcolor,prmytextcolor,secdrytextcolor,acctcolor,secacctcolor,tertaccentcolor);setItem("theme","custom");customtheme.classList.add('active-theme-button');break;default:setDefaultTheme();setItem("theme","default");defaulttheme.classList.add('active-theme-button');}}
function httpsUrl(url){if(!(url.includes("http"))){return "https://"+url;}
if(url.includes("http://")){urlParse=url.split("http://");return "https://"+urlParse[1];}
if(url.includes("https://")){return url;}}
function abcloakOption(){if((window.top.location.href!=="about:blank"&&abcloakelement.checked==true)&&getItem("abcloakingstatus")=="true"){confirmabcloak.style.visibility="visible";return}
if(abcloakelement.checked==false&&getItem("abcloakingstatus")=="false"){confirmnormal.style.visibility="visible";return}
if((window.top.location.href!=="about:blank"&&abcloakelement.checked==true)&&getItem("abcloakingstatus")=="false"){confirmabcloak.style.visibility="visible";setItem("abcloakingstatus","true");return}
if((window.top.location.href=="about:blank"&&abcloakelement.checked==false)&&getItem("abcloakingstatus")=="true"){confirmnormal.style.visibility="visible";setItem("abcloakingstatus","false");return}}
function abCloak(url){win=window.open();win.document.body.style.margin='0';win.document.body.style.height='100vh';var iframe=win.document.createElement('iframe');iframe.style.border='none';iframe.style.width='100%';iframe.style.height='100%';iframe.style.margin='0';iframe.src=url;iframe.id="embed";var preventionscript=win.document.createElement('script');preventionscript.src=getItem("site")+"/js/iframechecker.js";win.document.body.appendChild(iframe);win.document.body.appendChild(preventionscript);if(window.top.location.href!=='about:blank'){window.location.replace('https://google.com');}}
panicurlinput.addEventListener('change',function(){panicurl=panicurlinput.value;setItem("panicurl",panicurlinput.value);});panickeyinput.addEventListener('change',function(){panickey=panickeyinput.value;setItem("panickey",panickeyinput.value);});function normalSite(){window.open(getItem("site"));}
function abCloakPromptClose(event){event.stopPropagation();document.getElementById('confirmabcloak').style.visibility='hidden';abcloakelement.checked=false;setItem("abcloakingstatus","false");}
function normalPromptClose(event){event.stopPropagation();document.getElementById('confirmnormal').style.visibility='hidden';abcloakelement.checked=true;setItem("abcloakingstatus","true");}
function tabCloakTitle(){document.title=tabinput.value;setItem("pagetitle",tabinput.value);tabinput.value="";}
function tabCloakIcon(){favicon.href=httpsUrl(tabinput.value);setItem("pageiconurl",httpsUrl(tabinput.value));tabinput.value="";}
function tabCloakReset(){document.title="My Drive - Google Drive";setItem("pagetitle","My Drive - Google Drive");favicon.href="favicon.ico";setItem("pageiconurl","favicon.ico");}
function getItem(key){return localStorage.getItem(key);}
function setItem(key,value){localStorage.setItem(key,value);}
function getRootProperty(property){let style=getComputedStyle(rootelement);return style.getPropertyValue(property);}
function setRootProperty(property,value){rootelement.style.setProperty(property,value);}
function setDefaultTheme(){setRootProperty("--backgroundcolor","#35b3fa");setRootProperty("--primarytextcolor","black");setRootProperty("--secondarytextcolor","white");setRootProperty("--accentcolor","#9ad9fc");setRootProperty("--secondaryaccentcolor","#d1cfcf");setRootProperty("--tertiaryaccentcolor","darkgray");setRootProperty("--primary-font","'Dosis', sans-serif");}
function setDarkTheme(){setRootProperty("--backgroundcolor","rgb(20, 19, 19)");setRootProperty("--primarytextcolor","rgb(241, 234, 234)");setRootProperty("--secondarytextcolor","rgb(82, 81, 81)");setRootProperty("--accentcolor","#706c6f");setRootProperty("--secondaryaccentcolor","#2b2a2a");setRootProperty("--tertiaryaccentcolor","rgb(26, 25, 25)");setRootProperty("--primary-font","'Dosis', sans-serif");}
function setOceanTheme(){setRootProperty("--backgroundcolor","#C5F7EB");setRootProperty("--primarytextcolor","#5b828e");setRootProperty("--secondarytextcolor","#bbcfd7");setRootProperty("--accentcolor","#b9c4fa");setRootProperty("--secondaryaccentcolor","#d5f0f4");setRootProperty("--tertiaryaccentcolor","#d5f0f4");setRootProperty("--primary-font","'Dosis', sans-serif");}
function setMorningTheme(){setRootProperty("--backgroundcolor","#231a39");setRootProperty("--primarytextcolor","#fdd8a4");setRootProperty("--secondarytextcolor","#d0978e");setRootProperty("--accentcolor","#faac7b");setRootProperty("--secondaryaccentcolor","#9d7381");setRootProperty("--tertiaryaccentcolor","#faac7b");setRootProperty("--primary-font","'Dosis', sans-serif");}
function setCherryTheme(){setRootProperty("--backgroundcolor","#ec275f");setRootProperty("--primarytextcolor","#95c1f5");setRootProperty("--secondarytextcolor","#ffbfcd");setRootProperty("--accentcolor","#ffdcdc");setRootProperty("--secondaryaccentcolor","#ffa7a6");setRootProperty("--tertiaryaccentcolor","#d69090");setRootProperty("--primary-font","'Dosis', sans-serif");}
function setNightTheme(){setRootProperty("--backgroundcolor","#5a5a97");setRootProperty("--primarytextcolor","#010015");setRootProperty("--secondarytextcolor","#0f0f41");setRootProperty("--accentcolor","#02012c");setRootProperty("--secondaryaccentcolor","#313163");setRootProperty("--tertiaryaccentcolor","#2929ab");setRootProperty("--primary-font","'Dosis', sans-serif");}
function setSeasonalTheme(){setRootProperty("--backgroundcolor","#165b33");setRootProperty("--primarytextcolor","#fa636c");setRootProperty("--secondarytextcolor","#8ea763");setRootProperty("--accentcolor","#e7e0d6");setRootProperty("--secondaryaccentcolor","#bb2528");setRootProperty("--tertiaryaccentcolor","#9c1e20");setRootProperty("--primary-font","'Dosis', sans-serif");}
function setCustomTheme(fontFamily,color1,color2,color3,color4,color5,color6){setRootProperty("--backgroundcolor",color1);setRootProperty("--primarytextcolor",color2);setRootProperty("--secondarytextcolor",color3);setRootProperty("--accentcolor",color4);setRootProperty("--secondaryaccentcolor",color5);setRootProperty("--tertiaryaccentcolor",color6);setRootProperty("--primary-font",`'${fontFamily}', sans-serif`);if(!fontFamily){setRootProperty("--primary-font",`'Dosis', sans-serif`);}}